### ISSUE TITLE
Issues with the current version of backtrader

### ISSUE THREAD

**Issue by andreasemer** [hackingthemarkets/sentiment-fear-and-greed#1]
There are error messages in the current version of backtrader as you can read here https://community.backtrader.com/topic/981/importerror-cannot-import-name-min_per_hour-when-trying-to-plot/9 for example. 

The correct requirements should be definded in a requirements.txt, the Readme.md should be improved.

**Comment by andreasemer** [comment]
There is a PR here https://github.com/hackingthemarkets/sentiment-fear-and-greed/pulls

**Comment by hackingthemarkets** [comment]
Thanks for contributing a PR, much appreciated.
